global:
  scrape_interval: 15s

otlp:
  # Ingest OTLP data keeping UTF-8 characters in metric/label names.
  translation_strategy: NoUTF8EscapingWithSuffixes
  allow_delta: true

scrape_configs:
  - job_name: 'demo'
    static_configs:
      - targets: ['host.docker.internal:2112']
